# @package datamodule
defaults:
  - /datamodule/semantic/dales.yaml # General dataset parameters (metadata, augmentations)
  - /datamodule/partition/dales_ezsp.yaml # Partition parameters
  - /datamodule/semantic/default_ezsp.yaml # Semantic task parameters for EZ-SP

# Use `python src/train.py experiment=partition/dales.yaml`
# to pretrain the CNN and override the `pretrained_cnn_ckpt_path` field with
# your own checkpoint path.
pretrained_cnn_dim_without_in_dim: [32, 32, 32]
pretrained_cnn_kernel_size: [7, 3, 3]

# Parameter defining the 3 partition levels.
contour_prior_min_size: [5, 15, 70]

# Inputs.
partition_hf:
- 'intensity'

post_cnn_point_hf:
- 'intensity'
- 'elevation'

# As there is no RGB in DALES, we desactivate the RGB augmentations 
# to be able to use the same on_device_train_transform as for other datasets.
# The transforms are defined in `datamodule/semantic/default_ezsp.yaml`.
rgb_jitter: 0.0 
rgb_autocontrast: 0.0
rgb_drop: 0.0