# @package datamodule
defaults:
  - /datamodule/semantic/s3dis.yaml # General dataset parameters
  - /datamodule/partition/s3dis_ezsp.yaml # Partition parameters
  - /datamodule/semantic/default_ezsp.yaml # Semantic task parameters for EZ-SP

# Use `python src/train.py experiment=partition/s3dis.yaml`
# to pretrain the CNN and override the `pretrained_cnn_ckpt_path` field with
# your own checkpoint path.
pretrained_cnn_dim_without_in_dim: [32, 32, 32]
pretrained_cnn_kernel_size: 3

# Parameter defining the 3 partition levels.
contour_prior_min_size: [5,30,90]

# Inputs.
partition_hf:
 - 'rgb'

post_cnn_point_hf:
  - 'elevation'
  - 'rgb'