# @package datamodule
defaults:
  - /datamodule/semantic/default.yaml

_target_: src.datamodules.s3dis.S3DISDataModule

dataloader:
    batch_size: 1

# These parameters are not actually used by the DataModule, but are used
# here to facilitate model parameterization with config interpolation
num_classes: 13
stuff_classes: []
fold: 5
trainval: True
val_on_test: True
xy_tiling: null
in_memory: True  # set to True to load all processed S3DIS in RAM. This may accelerate training but CAREFUL not to modify the data in place !

# Features that will be computed, saved, loaded for points and segments

# point features used for the partition
partition_hf:
  - 'rgb'
  - 'linearity'
  - 'planarity'
  - 'scattering'
  - 'verticality'
  - 'elevation'

# point features used for training
point_hf:
  - 'linearity'
  - 'planarity'
  - 'scattering'
  - 'verticality'
  - 'elevation'
  - 'rgb'

# segment-wise features computed at preprocessing
segment_base_hf: []

# segment features computed as the mean of point feature in each
# segment, saved with "mean_" prefix
segment_mean_hf: []

# segment features computed as the std of point feature in each segment,
# saved with "std_" prefix
segment_std_hf: []

# horizontal edge features used for training
edge_hf:
  - 'mean_off'
  - 'std_off'
  - 'mean_dist'
  - 'angle_source'
  - 'angle_target'
  - 'centroid_dir'
  - 'centroid_dist'
  - 'normal_angle'
  - 'log_length'
  - 'log_surface'
  - 'log_volume'
  - 'log_size'

v_edge_hf: []  # vertical edge features used for training

# Parameters declared here to facilitate tuning configs without copying
# all the pre_transforms

# Based on SPG: https://arxiv.org/pdf/1711.09869.pdf
voxel: 0.03
knn: 45
knn_r: 2
knn_step: -1
knn_min_search: 25
ground_model: 'ransac'
ground_threshold: 1.5
ground_xy_grid: 1
ground_scale: 4.0
pcp_regularization: [0.01, 0.1, 0.5]
pcp_spatial_weight: [1e-1, 1e-1, 1e-1]
pcp_cutoff: [10, 10, 10]
pcp_edge_reduce: 'mean'
pcp_k_adjacency: 10
pcp_w_adjacency: 1
pcp_iterations: 15
graph_k_min: 1
graph_k_max: 30
graph_gap: [0.2, 0.5, 1]
graph_se_ratio: 0.3
graph_se_min: 20
graph_cycles: 3
graph_margin: 0.2
graph_chunk: [1e6, 1e5, 1e5]  # reduce if CUDA memory errors

# Batch construction parameterization
sample_segment_ratio: 0.1
sample_segment_by_size: True
sample_segment_by_class: False
sample_point_min: 32
sample_point_max: 128
sample_graph_r: 7  # set to r<=0 to skip SampleRadiusSubgraphs
sample_graph_k: 4
sample_graph_max_nodes: 10000
sample_graph_disjoint: True
sample_graph_cylindrical: False
sample_edge_n_min: -1  # [5, 5, 15]
sample_edge_n_max: -1  # [10, 15, 25]

# Augmentations parameterization
pos_jitter: 0.03
tilt_n_rotate_phi: 0.1
tilt_n_rotate_theta: 180
anisotropic_scaling: 0.2
rgb_jitter: 0
rgb_autocontrast: 0.5
rgb_drop: 0.3
node_feat_jitter: 0.01
h_edge_feat_jitter: 0.01
v_edge_feat_jitter: 0
node_feat_drop: 0.3
h_edge_feat_drop: 0
v_edge_feat_drop: 0
node_row_drop: 0
h_edge_row_drop: 0
v_edge_row_drop: 0
drop_to_mean: False